[build]
  base = "web/"
  command = "npm run build"
  publish = "/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# build a staging build for the `staging` branch
[context.storybook]
  command = "npm run build-storybook"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
